### ISSUE TITLE
.then function only get's called the first time when using $promise

### ISSUE THREAD

**Issue by mgamsjager** [goodeggs/angular-cached-resource#77]
When using $promise the .then() function only gets called a single time. The second time (when the actual data from the server returns) the scope gets updated but the .then function is not called.

Which means all extra business logic in this function is not added which returns half results compared when using $httpPromise (which does not use the cache at all afaik).

**Comment by demands** [comment]
Hi @mgamsjager. That's by design! It seems bad form to have a `then()` callback get called multiple times.

If you'd like the same behavior to happen when the cache loads, and then again when the data comes back, I recommend using a defined function and referring to it twice, like this:

```javascript
function handler () {
  /** do stuff with resource here **/
}
resource.$promise.then(handler);
resource.$httpPromise.then(handler);
```
